#!/usr/bin/env python3
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.
"""Generates app/EngineStringTable.h from the shipping engine resources.

CalcManager asks its IResourceProvider for every id in EngineStrings.h's g_sids.
The shipping app answers from CEngineStrings.resw; this bakes the same en-US
values in, plus the handful of labels the app renders from XAML rather than that
resource file (digits, memory keys) so history and expression tokens read the
same way.
"""

import os
import xml.etree.ElementTree as ET

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.normpath(os.path.join(HERE, "..", ".."))
RESW = os.path.join(SRC, "Calculator", "Resources", "en-US", "CEngineStrings.resw")
OUT = os.path.normpath(os.path.join(HERE, "..", "app", "EngineStringTable.h"))

# Rendered by the app's own XAML rather than CEngineStrings.resw; supplying them
# keeps expression and history tokens readable instead of blank.
FILL = {
    "0": "\u00b1", "1": "C", "3": "\u232b", "5": "", "31": "sqr", "32": "cube",
    "33": "fact", "34": "1/", "39": "e", "42": "MC", "43": "MR", "44": "MS",
    "45": "M+", "46": "M-", "50": "0", "51": "1", "52": "2", "53": "3", "54": "4",
    "55": "5", "56": "6", "57": "7", "58": "8", "59": "9", "60": "A", "61": "B",
    "62": "C", "63": "D", "64": "E", "65": "F", "93": "cuberoot",
    "102": "\u221e", "103": "-\u221e", "104": "Aborted", "106": "Too many digits",
    "109": "Insufficient data", "111": "Unknown character", "112": "Unknown function",
    "113": "Unexpected number", "114": "Unexpected character", "115": "Unexpected size",
    "116": "Mismatched parenthesis", "117": "Unexpected end of expression",
}


def esc(text):
    out = ""
    for ch in text:
        o = ord(ch)
        if ch == '"':
            out += '\\"'
        elif ch == "\\":
            out += "\\\\"
        elif 32 <= o < 127:
            out += ch
        else:
            out += '\\x%04x""' % o
    return out


def main():
    tree = ET.parse(RESW)
    values = {e.get("name"): (e.find("value").text or "") for e in tree.getroot().findall("data")}
    for key, value in FILL.items():
        values.setdefault(key, value)

    rows = sorted(values.items(), key=lambda kv: (len(kv[0]), kv[0]))
    lines = [
        "// Copyright (c) Microsoft Corporation. All rights reserved.",
        "// Licensed under the MIT License.",
        "//",
        "// GENERATED by tools/gen_engine_strings.py from",
        "// src/Calculator/Resources/en-US/CEngineStrings.resw -- do not edit by hand.",
        "",
        "#pragma once",
        "",
        "#include <array>",
        "",
        "namespace CalcCompact",
        "{",
        "    // Plain pointers rather than string views: the table is scanned once per",
        "    // lookup either way, and this halves both its size and its relocations.",
        "    struct EngineString",
        "    {",
        "        const wchar_t* id;",
        "        const wchar_t* value;",
        "    };",
        "",
        "    inline constexpr std::array<EngineString, %d> kEngineStrings = {{" % len(rows),
    ]
    for key, value in rows:
        lines.append('        { L"%s", L"%s" },' % (esc(key), esc(value)))
    lines.append("    }};")
    lines.append("}")

    with open(OUT, "w", encoding="utf-8") as handle:
        handle.write("\n".join(lines) + "\n")
    print("wrote %s: %d strings" % (OUT, len(rows)))


if __name__ == "__main__":
    main()
