// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
//
// GENERATED by tools/gen_converter_data.py -- do not edit by hand.
// Sources: Calculator.ViewModels/DataLoaders/UnitConverterDataLoader.cs,
//          Calculator.ViewModels/Common/NavCategory.cs,
//          Calculator/Resources/en-US/Resources.resw

#pragma once

#include <array>

namespace CalcCompact
{
    // Fields are ordered widest-first and use plain pointers rather than
    // string views: at 158 units the padding and the extra relocations were
    // worth several KB of the binary.
    struct ConverterUnit
    {
        double factor;        // relative to the category's base unit
        const wchar_t* name;
        const wchar_t* abbreviation;
        int id;
        bool isConversionSource;
        bool isConversionTarget;
        bool isWhimsical;     // shown only in the suggested-values list
    };

    struct ConverterExplicitConversion
    {
        int fromId;
        int toId;
        double ratio;
        double offset;
        bool offsetFirst;
    };

    struct ConverterCategory
    {
        const ConverterUnit* units;
        const ConverterExplicitConversion* explicitConversions;
        const wchar_t* name;
        const wchar_t* glyph;
        unsigned short unitCount;
        unsigned short explicitCount;
        unsigned short id;
        bool supportsNegative;
    };

    inline constexpr std::array<ConverterUnit, 23> kVolumeUnits = {{
        { 1.0, L"Milliliters", L"mL", 75, true, false, false },
        { 1.0, L"Cubic centimeters", L"cm\x00b3""", 64, false, false, false },
        { 1000.0, L"Liters", L"L", 74, false, false, false },
        { 1000000.0, L"Cubic meters", L"m\x00b3""", 67, false, false, false },
        { 4.92892159375, L"Teaspoons (US)", L"tsp. (US)", 79, false, true, false },
        { 14.78676478125, L"Tablespoons (US)", L"tbsp. (US)", 78, false, false, false },
        { 29.5735295625, L"Fluid ounces (US)", L"fl oz (US)", 71, false, false, false },
        { 236.588237, L"Cups (US)", L"cup (US)", 69, false, false, false },
        { 473.176473, L"Pints (US)", L"pt (US)", 77, false, false, false },
        { 946.352946, L"Quarts (US)", L"qt (US)", 81, false, false, false },
        { 3785.411784, L"Gallons (US)", L"gal (US)", 73, false, false, false },
        { 16.387064, L"Cubic inches", L"in\x00b3""", 66, false, false, false },
        { 28316.846592, L"Cubic feet", L"ft\x00b3""", 65, false, false, false },
        { 764554.857984, L"Cubic yards", L"yd\x00b3""", 68, false, false, false },
        { 5.919388020833333, L"Teaspoons (UK)", L"tsp. (UK)", 115, false, false, false },
        { 17.7581640625, L"Tablespoons (UK)", L"tbsp. (UK)", 116, false, false, false },
        { 28.4130625, L"Fluid ounces (UK)", L"fl oz (UK)", 70, false, false, false },
        { 568.26125, L"Pints (UK)", L"pt (UK)", 76, false, false, false },
        { 1136.5225, L"Quarts (UK)", L"qt (UK)", 80, false, false, false },
        { 4546.09, L"Gallons (UK)", L"gal (UK)", 72, false, false, false },
        { 236.5882, L"coffee cups", L"coffee cups", 124, false, false, true },
        { 378541.2, L"bathtubs", L"bathtubs", 111, false, false, true },
        { 3750000000.0, L"swimming pools", L"swimming pools", 125, false, false, true },
    }};

    inline constexpr std::array<ConverterUnit, 15> kLengthUnits = {{
        { 1e-10, L"Angstroms", L"A", 168, false, false, false },
        { 1e-09, L"Nanometers", L"nm", 38, false, false, false },
        { 1e-06, L"Microns", L"\x00b5""m", 35, false, false, false },
        { 0.001, L"Millimeters", L"mm", 37, false, false, false },
        { 0.01, L"Centimeters", L"cm", 30, true, false, false },
        { 1.0, L"Meters", L"m", 34, false, false, false },
        { 1000.0, L"Kilometers", L"km", 33, false, false, false },
        { 0.0254, L"Inches", L"in", 32, false, true, false },
        { 0.3048, L"Feet", L"ft", 31, false, false, false },
        { 0.9144, L"Yards", L"yd", 40, false, false, false },
        { 1609.344, L"Miles", L"mi", 36, false, false, false },
        { 1852.0, L"Nautical miles", L"nmi", 39, false, false, false },
        { 0.035052, L"paperclips", L"paperclips", 105, false, false, true },
        { 0.18669, L"hands", L"hands", 131, false, false, true },
        { 76.0, L"jumbo jets", L"jumbo jets", 107, false, false, true },
    }};

    inline constexpr std::array<ConverterUnit, 18> kWeightUnits = {{
        { 0.0002, L"Carats", L"CD", 82, false, false, false },
        { 1e-06, L"Milligrams", L"mg", 90, false, false, false },
        { 1e-05, L"Centigrams", L"cg", 83, false, false, false },
        { 0.0001, L"Decigrams", L"dg", 84, false, false, false },
        { 0.001, L"Grams", L"g", 86, false, false, false },
        { 0.01, L"Dekagrams", L"dag", 85, false, false, false },
        { 0.1, L"Hectograms", L"hg", 87, false, false, false },
        { 1.0, L"Kilograms", L"kg", 88, true, false, false },
        { 1000.0, L"Metric tonnes", L"t", 95, false, false, false },
        { 0.028349523125, L"Ounces", L"oz", 91, false, false, false },
        { 0.45359237, L"Pounds", L"lb", 92, false, true, false },
        { 6.35029318, L"Stone", L"st", 94, false, false, false },
        { 907.18474, L"Short tons (US)", L"ton (US)", 93, false, false, false },
        { 1016.0469088, L"Long tons (UK)", L"ton (UK)", 89, false, false, false },
        { 2e-06, L"snowflakes", L"snowflakes", 113, false, false, true },
        { 0.4325, L"soccer balls", L"soccer balls", 133, false, false, true },
        { 4000.0, L"elephants", L"elephants", 114, false, false, true },
        { 90000.0, L"whales", L"whales", 123, false, false, true },
    }};

    inline constexpr std::array<ConverterUnit, 3> kTemperatureUnits = {{
        { 0.0, L"Celsius", L"\x00b0""C", 46, true, false, false },
        { 0.0, L"Fahrenheit", L"\x00b0""F", 47, false, true, false },
        { 0.0, L"Kelvin", L"K", 48, false, false, false },
    }};

    inline constexpr std::array<ConverterUnit, 11> kEnergyUnits = {{
        { 1.602176565e-19, L"Electron volts", L"eV", 25, false, false, false },
        { 1.0, L"Joules", L"J", 27, true, false, false },
        { 1000.0, L"Kilojoules", L"kJ", 29, false, false, false },
        { 4.184, L"Thermal calories", L"cal", 24, false, false, false },
        { 4184.0, L"Food calories", L"kcal", 28, false, true, false },
        { 1.3558179483314, L"Foot-pounds", L"ft\x2022""lb", 26, false, false, false },
        { 1055.056, L"British thermal units", L"BTU", 23, false, false, false },
        { 9000.0, L"batteries", L"batteries", 103, false, false, true },
        { 439614.0, L"bananas", L"bananas", 129, false, false, true },
        { 1046700.0, L"slices of cake", L"slices of cake", 130, false, false, true },
        { 3600000.0, L"Kilowatt-hours", L"kWh", 166, true, false, false },
    }};

    inline constexpr std::array<ConverterUnit, 15> kAreaUnits = {{
        { 1e-06, L"Square millimeters", L"mm\x00b2""", 9, false, false, false },
        { 0.0001, L"Square centimeters", L"cm\x00b2""", 3, false, false, false },
        { 1.0, L"Square meters", L"m\x00b2""", 7, true, false, false },
        { 10000.0, L"Hectares", L"ha", 2, false, false, false },
        { 1000000.0, L"Square kilometers", L"km\x00b2""", 6, false, false, false },
        { 0.00064516, L"Square inches", L"in\x00b2""", 5, false, false, false },
        { 0.09290304, L"Square feet", L"ft\x00b2""", 4, false, true, false },
        { 0.83612736, L"Square yards", L"yd\x00b2""", 10, false, false, false },
        { 4046.8564224, L"Acres", L"ac", 1, false, false, false },
        { 2589988.110336, L"Square miles", L"mi\x00b2""", 8, false, false, false },
        { 0.012516104, L"hands", L"hands", 118, false, false, true },
        { 0.06032246, L"sheets of paper", L"sheets of paper", 127, false, false, true },
        { 10869.66, L"soccer fields", L"soccer fields", 99, false, false, true },
        { 100000.0, L"castles", L"castles", 128, false, false, true },
        { 3.3057851239669422, L"Pyeong", L"Pyeong", 165, false, false, false },
    }};

    inline constexpr std::array<ConverterUnit, 10> kSpeedUnits = {{
        { 1.0, L"Centimeters per second", L"cm/s", 57, false, false, false },
        { 100.0, L"Meters per second", L"m/s", 62, false, false, false },
        { 27.77777777777778, L"Kilometers per hour", L"km/h", 59, true, false, false },
        { 30.48, L"Feet per second", L"ft/s", 58, false, false, false },
        { 44.7, L"Miles per hour", L"mph", 63, false, true, false },
        { 51.44, L"Knots", L"kn", 60, false, false, false },
        { 34030.0, L"Mach", L"M", 61, false, false, false },
        { 8.94, L"turtles", L"turtles", 121, false, false, true },
        { 2011.5, L"horses", L"horses", 126, false, false, true },
        { 24585.0, L"jets", L"jets", 122, false, false, true },
    }};

    inline constexpr std::array<ConverterUnit, 8> kTimeUnits = {{
        { 1e-06, L"Microseconds", L"\x00b5""s", 51, false, false, false },
        { 0.001, L"Milliseconds", L"ms", 52, false, false, false },
        { 1.0, L"Seconds", L"s", 54, false, false, false },
        { 60.0, L"Minutes", L"min", 53, false, true, false },
        { 3600.0, L"Hours", L"hr", 50, true, false, false },
        { 86400.0, L"Days", L"d", 49, false, false, false },
        { 604800.0, L"Weeks", L"wk", 55, false, false, false },
        { 31557600.0, L"Years", L"yr", 56, false, false, false },
    }};

    inline constexpr std::array<ConverterUnit, 8> kPowerUnits = {{
        { 1.0, L"Watts", L"W", 45, false, false, false },
        { 1000.0, L"Kilowatts", L"kW", 44, true, false, false },
        { 745.6998715822702, L"Horsepower (US)", L"hp (US)", 43, false, true, false },
        { 0.0225969658055233, L"Foot-pounds/minute", L"ft\x2022""lb/min", 42, false, false, false },
        { 17.58426666666667, L"BTUs/minute", L"BTU/min", 41, false, false, false },
        { 60.0, L"light bulbs", L"light bulbs", 108, false, false, true },
        { 745.7, L"horses", L"horses", 109, false, false, true },
        { 2982799.486329081, L"train engines", L"train engines", 132, false, false, true },
    }};

    inline constexpr std::array<ConverterUnit, 38> kDataUnits = {{
        { 1.25e-07, L"Bits", L"b", 11, false, false, false },
        { 5e-07, L"Nibble", L"nybl", 167, false, false, false },
        { 1e-06, L"Bytes", L"B", 12, false, false, false },
        { 0.000125, L"Kilobits", L"Kb", 15, false, false, false },
        { 0.000128, L"Kibibits", L"Ki", 149, false, false, false },
        { 0.001, L"Kilobytes", L"KB", 16, false, false, false },
        { 0.001024, L"Kibibytes", L"KiB", 150, false, false, false },
        { 0.125, L"Megabits", L"Mb", 17, false, false, false },
        { 0.131072, L"Mebibits", L"Mi", 151, false, false, false },
        { 1.0, L"Megabytes", L"MB", 18, false, true, false },
        { 1.048576, L"Mebibytes", L"MiB", 152, false, false, false },
        { 125.0, L"Gigabits", L"Gb", 13, false, false, false },
        { 134.217728, L"Gibibits", L"Gi", 147, false, false, false },
        { 1.47456, L"floppy disks", L"floppy disks", 100, false, false, true },
        { 1000.0, L"Gigabytes", L"GB", 14, true, false, false },
        { 700.0, L"CDs", L"CDs", 101, false, false, true },
        { 1073.741824, L"Gibibytes", L"GiB", 148, false, false, false },
        { 4700.0, L"DVDs", L"DVDs", 102, false, false, true },
        { 125000.0, L"Terabits", L"Tb", 21, false, false, false },
        { 137438.953472, L"Tebibits", L"Ti", 155, false, false, false },
        { 1000000.0, L"Terabytes", L"TB", 22, false, false, false },
        { 1099511.627776, L"Tebibytes", L"TiB", 156, false, false, false },
        { 125000000.0, L"Petabits", L"Pb", 19, false, false, false },
        { 140737488.355328, L"Pebibits", L"Pi", 153, false, false, false },
        { 1000000000.0, L"Petabytes", L"PB", 20, false, false, false },
        { 1125899906.842624, L"Pebibytes", L"PiB", 154, false, false, false },
        { 125000000000.0, L"Exabits", L"E", 143, false, false, false },
        { 144115188075.85587, L"Exbibits", L"Ei", 145, false, false, false },
        { 1000000000000.0, L"Exabytes", L"EB", 144, false, false, false },
        { 1152921504606.847, L"Exbibytes", L"EiB", 146, false, false, false },
        { 125000000000000.0, L"Zetabits", L"Z", 163, false, false, false },
        { 147573952589676.4, L"Zebibits", L"Zi", 161, false, false, false },
        { 1000000000000000.0, L"Zetabytes", L"ZB", 164, false, false, false },
        { 1180591620717411.2, L"Zebibytes", L"ZiB", 162, false, false, false },
        { 1.25e+17, L"Yottabits", L"Y", 159, false, false, false },
        { 1.5111572745182864e+17, L"Yobibits", L"Yi", 157, false, false, false },
        { 1e+18, L"Yottabytes", L"YB", 160, false, false, false },
        { 1.208925819614629e+18, L"Yobibytes", L"YiB", 158, false, false, false },
    }};

    inline constexpr std::array<ConverterUnit, 6> kPressureUnits = {{
        { 1.0, L"Atmospheres", L"atm", 137, true, false, false },
        { 0.9869232667160128, L"Bars", L"ba", 138, false, true, false },
        { 0.0098692326671601, L"Kilopascals", L"kPa", 139, false, false, false },
        { 0.0013155687145324, L"Millimeters of mercury ", L"mmHg", 140, false, false, false },
        { 9.869232667160129e-06, L"Pascals", L"Pa", 141, false, false, false },
        { 0.068045961016531, L"Pounds per square inch", L"psi", 142, false, false, false },
    }};

    inline constexpr std::array<ConverterUnit, 3> kAngleUnits = {{
        { 1.0, L"Degrees", L"deg", 134, true, false, false },
        { 57.29577951308233, L"Radians", L"rad", 135, false, true, false },
        { 0.9, L"Gradians", L"grad", 136, false, false, false },
    }};

    inline constexpr std::array<ConverterExplicitConversion, 9> kTemperatureConversions = {{
        { 46, 46, 1.0, 0.0, false },
        { 46, 47, 1.8, 32.0, false },
        { 46, 48, 1.0, 273.15, false },
        { 47, 46, 0.5555555555555556, -32.0, true },
        { 47, 47, 1.0, 0.0, false },
        { 47, 48, 0.5555555555555556, 459.67, true },
        { 48, 46, 1.0, -273.15, true },
        { 48, 47, 1.8, -459.67, false },
        { 48, 48, 1.0, 0.0, false },
    }};

    inline constexpr std::array<ConverterCategory, 12> kConverterCategories = {{
        { kVolumeUnits.data(), nullptr, L"Volume", L"\uF1AA", static_cast<unsigned short>(kVolumeUnits.size()), static_cast<unsigned short>(0), 4, false },
        { kLengthUnits.data(), nullptr, L"Length", L"\uECC6", static_cast<unsigned short>(kLengthUnits.size()), static_cast<unsigned short>(0), 5, false },
        { kWeightUnits.data(), nullptr, L"Weight and mass", L"\uF4C1", static_cast<unsigned short>(kWeightUnits.size()), static_cast<unsigned short>(0), 6, false },
        { kTemperatureUnits.data(), kTemperatureConversions.data(), L"Temperature", L"\uE7A3", static_cast<unsigned short>(kTemperatureUnits.size()), static_cast<unsigned short>(kTemperatureConversions.size()), 7, true },
        { kEnergyUnits.data(), nullptr, L"Energy", L"\uECAD", static_cast<unsigned short>(kEnergyUnits.size()), static_cast<unsigned short>(0), 8, false },
        { kAreaUnits.data(), nullptr, L"Area", L"\uE809", static_cast<unsigned short>(kAreaUnits.size()), static_cast<unsigned short>(0), 9, false },
        { kSpeedUnits.data(), nullptr, L"Speed", L"\uEADA", static_cast<unsigned short>(kSpeedUnits.size()), static_cast<unsigned short>(0), 10, false },
        { kTimeUnits.data(), nullptr, L"Time", L"\uE917", static_cast<unsigned short>(kTimeUnits.size()), static_cast<unsigned short>(0), 11, false },
        { kPowerUnits.data(), nullptr, L"Power", L"\uE945", static_cast<unsigned short>(kPowerUnits.size()), static_cast<unsigned short>(0), 12, true },
        { kDataUnits.data(), nullptr, L"Data", L"\uF20F", static_cast<unsigned short>(kDataUnits.size()), static_cast<unsigned short>(0), 13, false },
        { kPressureUnits.data(), nullptr, L"Pressure", L"\uEC4A", static_cast<unsigned short>(kPressureUnits.size()), static_cast<unsigned short>(0), 14, false },
        { kAngleUnits.data(), nullptr, L"Angle", L"\uF515", static_cast<unsigned short>(kAngleUnits.size()), static_cast<unsigned short>(0), 15, true },
    }};
}
